name: "CI Rust Rocket"

on: push

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust-rocket
    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check

      - name: Clippy fix
        run: cargo clippy --fix

      - name: Check no more Clippy errors
        run: cargo clippy -- -D warnings

      - name: Format
        run: cargo fmt

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -am "refactor(GHActionbot): :art: formatted & clippy" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Build
        run: ./build.sh

      - name: Test
        run: cargo test
