name: "CI Rust Dioxus"

on: push

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust-dioxus-web
    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/index
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install Dioxus CLI (dx)
        run: cargo install dioxus-cli

      - name: Check
        run: cargo check && dx check

      - name: Clippy fix
        run: cargo clippy --fix

      - name: Check no more Clippy errors
        run: cargo clippy -- -D warnings

      - name: Format
        run: cargo fmt && dx fmt

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -am "refactor(GHActionbot): :art: formatted & clippy" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Build
        run: cargo build && dx build

      - name: Test
        run: cargo test
